/*
 Navicat Premium Dump SQL

 Source Server         : 175.178.115.41
 Source Server Type    : MySQL
 Source Server Version : 90001 (9.0.1)
 Source Host           : 175.178.115.41:3316
 Source Schema         : tanzania_booking_training

 Target Server Type    : MySQL
 Target Server Version : 90001 (9.0.1)
 File Encoding         : 65001

 Date: 11/07/2026 01:36:54
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for tbl_cargo_info_all
-- ----------------------------
DROP TABLE IF EXISTS `tbl_cargo_info_all`;
CREATE TABLE `tbl_cargo_info_all` (
  `id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键',
  `uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务主键（根据source_type类型，去区分对应的表，tbl_awb或者inter_report_detail）',
  `freight_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '运价id',
  `freight_detail_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '运价详情id',
  `report_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '账单id',
  `cal_flag` smallint NOT NULL COMMENT '标识 0 未计算；1 计算成功； 2 计算失败',
  `cal_time` datetime DEFAULT NULL COMMENT '最新计算时间',
  `freight_type` smallint DEFAULT NULL COMMENT '运价类型：0、基础运价 1、包量运价 2、杂费运价 3、包板运价 4、包舱运价 5、单票运价',
  `prefix` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '前缀',
  `cargo_no` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '单号',
  `awb_no` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '运单号',
  `awb_carrier` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '运单承运人',
  `international` tinyint DEFAULT NULL COMMENT '国内国际 1、国内  2、国际',
  `type` smallint DEFAULT NULL COMMENT '制单类型:0:代理人制单、1:货站制单',
  `source_type` smallint DEFAULT NULL COMMENT '数据来源：0：制单数据、1：代理人导入',
  `bill_status` smallint DEFAULT NULL COMMENT '是否开账：0：未开账、1：已开账',
  `check_status` smallint DEFAULT NULL COMMENT '是否审核：0：未审核、1：已审核',
  `ticket_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '票证id',
  `open_date` date NOT NULL COMMENT '开票日期',
  `airline_org_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '航司代码',
  `cargo_dep` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '运单始发站',
  `cargo_dest` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '运单目的站',
  `cargo_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '运单类型:1:货单AWB 2:邮单MAIL 3:其他运单OTH',
  `agent_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '代理人编码',
  `agent_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '代理人名称',
  `flight_no` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '航班号',
  `carrier` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '承运人',
  `airline_icao` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '航司ICAO码',
  `airline_icao1` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '航司ICAO码(第一程)',
  `flight_date` date NOT NULL COMMENT '航班日期',
  `dep` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '始发站',
  `dep_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '始发站名称',
  `dest` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '第一目的站',
  `dest_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '目的站名称',
  `dest1` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第一目的站',
  `arr` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '中转站',
  `flight_nature` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '航程',
  `flight_no2` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第二航班号',
  `airline_icao2` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '航司ICAO码(第二程)',
  `flight_date2` date DEFAULT NULL COMMENT '第二航班日期',
  `carrier2` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第二承运人',
  `dep2` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第二始发站',
  `dest2` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第二到达站',
  `flight_no3` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第三航班号',
  `airline_icao3` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '航司ICAO码(第三程)',
  `carrier3` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第三承运人',
  `flight_date3` date DEFAULT NULL COMMENT '第三航班日期',
  `dep3` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第三始发站',
  `dest3` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '第三到达站',
  `rate_class` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '运价种类',
  `rate_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '运价名称',
  `rate_type` int DEFAULT NULL COMMENT '费率类型 0为正常费率 1为一票一议 2为自动计算运价',
  `currency` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '币种',
  `goods_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '品名',
  `goods_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '结算货物类型',
  `goods_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '商品代码',
  `pc` int DEFAULT NULL COMMENT '件数',
  `weight` decimal(10,2) DEFAULT NULL COMMENT '重量',
  `charge_weight` decimal(10,2) DEFAULT NULL COMMENT '计费重量',
  `volume` decimal(30,2) DEFAULT NULL COMMENT '体积',
  `spcode` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '特码',
  `rate` decimal(10,2) DEFAULT NULL COMMENT '费率',
  `flight_fee` decimal(10,2) DEFAULT NULL COMMENT '航空运费',
  `fuel_fee` decimal(10,2) DEFAULT NULL COMMENT '燃油附加费',
  `awc` decimal(10,2) DEFAULT NULL COMMENT '制单费',
  `dvc` decimal(10,2) DEFAULT NULL COMMENT '声明价值附加费',
  `sfc` decimal(10,2) DEFAULT NULL COMMENT '地面运费',
  `tax` decimal(10,2) DEFAULT NULL COMMENT '税费',
  `other_fee` decimal(10,2) DEFAULT NULL COMMENT '其他费用',
  `total_amount` decimal(10,2) DEFAULT NULL COMMENT '总金额',
  `cal_flight_fee` decimal(10,2) DEFAULT NULL COMMENT '计算后航空费用',
  `cal_fuel_fee` decimal(10,2) DEFAULT NULL COMMENT '计算后燃油附加费',
  `cal_awc` decimal(10,2) DEFAULT NULL COMMENT '计算后制单费',
  `cal_dvc` decimal(10,2) DEFAULT NULL COMMENT '计算后的声明价值费',
  `cal_sfc` decimal(10,2) DEFAULT NULL COMMENT '计算后的地面运费',
  `cal_msc` decimal(10,2) DEFAULT NULL COMMENT '计算后的战保费',
  `cal_tax` decimal(10,2) DEFAULT NULL COMMENT '计算后的税',
  `cal_cca_fee` decimal(10,2) DEFAULT NULL COMMENT '计算后cca费用',
  `cal_other_fee` decimal(10,2) DEFAULT NULL COMMENT '计算后其他费用',
  `cal_total_other_fee` decimal(10,2) DEFAULT NULL COMMENT '计算后杂费合计',
  `cal_total_amount` decimal(10,2) DEFAULT NULL COMMENT '计算后总金额',
  `remark` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '创建人',
  `update_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='运单总表';

-- ----------------------------
-- Records of tbl_cargo_info_all
-- ----------------------------
BEGIN;
INSERT INTO `tbl_cargo_info_all` (`id`, `uuid`, `freight_id`, `freight_detail_id`, `report_id`, `cal_flag`, `cal_time`, `freight_type`, `prefix`, `cargo_no`, `awb_no`, `awb_carrier`, `international`, `type`, `source_type`, `bill_status`, `check_status`, `ticket_id`, `open_date`, `airline_org_code`, `cargo_dep`, `cargo_dest`, `cargo_type`, `agent_code`, `agent_name`, `flight_no`, `carrier`, `airline_icao`, `airline_icao1`, `flight_date`, `dep`, `dep_name`, `dest`, `dest_name`, `dest1`, `arr`, `flight_nature`, `flight_no2`, `airline_icao2`, `flight_date2`, `carrier2`, `dep2`, `dest2`, `flight_no3`, `airline_icao3`, `carrier3`, `flight_date3`, `dep3`, `dest3`, `rate_class`, `rate_name`, `rate_type`, `currency`, `goods_name`, `goods_type`, `goods_code`, `pc`, `weight`, `charge_weight`, `volume`, `spcode`, `rate`, `flight_fee`, `fuel_fee`, `awc`, `dvc`, `sfc`, `tax`, `other_fee`, `total_amount`, `cal_flight_fee`, `cal_fuel_fee`, `cal_awc`, `cal_dvc`, `cal_sfc`, `cal_msc`, `cal_tax`, `cal_cca_fee`, `cal_other_fee`, `cal_total_other_fee`, `cal_total_amount`, `remark`, `create_time`, `create_by`, `update_by`, `update_time`) VALUES ('2053776263246827521', 'b21d81f29dc368ac5cfc9cc429adbb6b', '543f00eeebb322c4434f4f1062aadc9e', 'e1fb9c53320748b78741b10cc84cfdfc', '76b9635758b22751a79f6f988b805139', 1, NULL, 0, '197', '00013020', '197-00013020', NULL, NULL, NULL, NULL, 1, 1, NULL, '2026-05-11', NULL, NULL, NULL, NULL, 'IT', 'iTran', 'TC5402', 'TC', NULL, NULL, '2026-05-11', 'DAR', NULL, 'CAN', NULL, NULL, NULL, 'DAR-CAN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TZS', '1', NULL, 'A', 1, 1.00, 166.67, 1.00, 'GEN', 4.00, 666.68, NULL, NULL, NULL, NULL, NULL, NULL, 666.68, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-11 17:56:33', 'admin', 'admin', '2026-05-15 00:48:18');
INSERT INTO `tbl_cargo_info_all` (`id`, `uuid`, `freight_id`, `freight_detail_id`, `report_id`, `cal_flag`, `cal_time`, `freight_type`, `prefix`, `cargo_no`, `awb_no`, `awb_carrier`, `international`, `type`, `source_type`, `bill_status`, `check_status`, `ticket_id`, `open_date`, `airline_org_code`, `cargo_dep`, `cargo_dest`, `cargo_type`, `agent_code`, `agent_name`, `flight_no`, `carrier`, `airline_icao`, `airline_icao1`, `flight_date`, `dep`, `dep_name`, `dest`, `dest_name`, `dest1`, `arr`, `flight_nature`, `flight_no2`, `airline_icao2`, `flight_date2`, `carrier2`, `dep2`, `dest2`, `flight_no3`, `airline_icao3`, `carrier3`, `flight_date3`, `dep3`, `dest3`, `rate_class`, `rate_name`, `rate_type`, `currency`, `goods_name`, `goods_type`, `goods_code`, `pc`, `weight`, `charge_weight`, `volume`, `spcode`, `rate`, `flight_fee`, `fuel_fee`, `awc`, `dvc`, `sfc`, `tax`, `other_fee`, `total_amount`, `cal_flight_fee`, `cal_fuel_fee`, `cal_awc`, `cal_dvc`, `cal_sfc`, `cal_msc`, `cal_tax`, `cal_cca_fee`, `cal_other_fee`, `cal_total_other_fee`, `cal_total_amount`, `remark`, `create_time`, `create_by`, `update_by`, `update_time`) VALUES ('2055190527183548417', 'c8310710c11e5c9707310565ab5c1723', '4c04a387b4236a084865fdda25828c28', '4c04a387b4236a084865fdda25828c28', 'dc25c2fffa1065523e450adcd52b0537', 1, NULL, 5, '197', '00013064', '197-00013064', NULL, NULL, NULL, NULL, 1, 1, NULL, '2026-05-14', NULL, NULL, NULL, NULL, 'IT', 'iTran', 'TC5402', 'TC', NULL, NULL, '2026-05-14', 'DAR', NULL, 'CAN', NULL, NULL, NULL, 'DAR-CAN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TZS', '1', NULL, 'A', 1, 1.00, 166.67, 1.00, 'GEN', 1000.00, 10000.00, NULL, NULL, NULL, NULL, NULL, 300.00, 10300.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 15:36:20', 'represent', 'represent', '2026-05-15 15:45:08');
INSERT INTO `tbl_cargo_info_all` (`id`, `uuid`, `freight_id`, `freight_detail_id`, `report_id`, `cal_flag`, `cal_time`, `freight_type`, `prefix`, `cargo_no`, `awb_no`, `awb_carrier`, `international`, `type`, `source_type`, `bill_status`, `check_status`, `ticket_id`, `open_date`, `airline_org_code`, `cargo_dep`, `cargo_dest`, `cargo_type`, `agent_code`, `agent_name`, `flight_no`, `carrier`, `airline_icao`, `airline_icao1`, `flight_date`, `dep`, `dep_name`, `dest`, `dest_name`, `dest1`, `arr`, `flight_nature`, `flight_no2`, `airline_icao2`, `flight_date2`, `carrier2`, `dep2`, `dest2`, `flight_no3`, `airline_icao3`, `carrier3`, `flight_date3`, `dep3`, `dest3`, `rate_class`, `rate_name`, `rate_type`, `currency`, `goods_name`, `goods_type`, `goods_code`, `pc`, `weight`, `charge_weight`, `volume`, `spcode`, `rate`, `flight_fee`, `fuel_fee`, `awc`, `dvc`, `sfc`, `tax`, `other_fee`, `total_amount`, `cal_flight_fee`, `cal_fuel_fee`, `cal_awc`, `cal_dvc`, `cal_sfc`, `cal_msc`, `cal_tax`, `cal_cca_fee`, `cal_other_fee`, `cal_total_other_fee`, `cal_total_amount`, `remark`, `create_time`, `create_by`, `update_by`, `update_time`) VALUES ('2055190527183548418', '8e0230678ad64f1d036da16fe824b6d7', 'ecd80eaf73ae4cd3efbe1803a360d0b0', '3bec243460b344ec99acc24e59945a35', 'dc25c2fffa1065523e450adcd52b0537', 1, NULL, 0, '197', '00013156', '197-00013156', NULL, NULL, NULL, NULL, 1, 1, NULL, '2026-05-15', NULL, NULL, NULL, NULL, 'IT', 'iTran', 'TC0511', 'TC', NULL, NULL, '2026-05-15', 'DAR', NULL, 'CAN', NULL, NULL, NULL, 'DAR-CAN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TZS', '1', NULL, 'A', 8, 11000.00, 11000.00, 10.00, 'GEN', 9.00, 99000.00, NULL, NULL, NULL, NULL, NULL, 330.00, 99330.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '2026-05-15 15:36:20', 'represent', 'represent', '2026-05-15 15:45:08');
INSERT INTO `tbl_cargo_info_all` (`id`, `uuid`, `freight_id`, `freight_detail_id`, `report_id`, `cal_flag`, `cal_time`, `freight_type`, `prefix`, `cargo_no`, `awb_no`, `awb_carrier`, `international`, `type`, `source_type`, `bill_status`, `check_status`, `ticket_id`, `open_date`, `airline_org_code`, `cargo_dep`, `cargo_dest`, `cargo_type`, `agent_code`, `agent_name`, `flight_no`, `carrier`, `airline_icao`, `airline_icao1`, `flight_date`, `dep`, `dep_name`, `dest`, `dest_name`, `dest1`, `arr`, `flight_nature`, `flight_no2`, `airline_icao2`, `flight_date2`, `carrier2`, `dep2`, `dest2`, `flight_no3`, `airline_icao3`, `carrier3`, `flight_date3`, `dep3`, `dest3`, `rate_class`, `rate_name`, `rate_type`, `currency`, `goods_name`, `goods_type`, `goods_code`, `pc`, `weight`, `charge_weight`, `volume`, `spcode`, `rate`, `flight_fee`, `fuel_fee`, `awc`, `dvc`, `sfc`, `tax`, `other_fee`, `total_amount`, `cal_flight_fee`, `cal_fuel_fee`, `cal_awc`, `cal_dvc`, `cal_sfc`, `cal_msc`, `cal_tax`, `cal_cca_fee`, `cal_other_fee`, `cal_total_other_fee`, `cal_total_amount`, `remark`, `create_time`, `create_by`, `update_by`, `update_time`) VALUES ('2055190527183548419', '54c8abd0ecd2741d21fd997b470eae7c', 'aff47c12979dcea16761ecdfd03baf0b', 'e9d486eef3464872ba34b1edebb460f4', 'dc25c2fffa1065523e450adcd52b0537', 1, NULL, 0, '197', '00013134', '197-00013134', NULL, NULL, NULL, NULL, 1, 1, NULL, '2026-05-14', NULL, NULL, NULL, NULL, 'IT', 'iTran', 'TC5402', 'TC', NULL, NULL, '2026-05-14', 'DAR', NULL, 'CAN', NULL, NULL, NULL, 'DAR-CAN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TZS', '1', NULL, 'A', 5, 554.00, 833.33, 5.00, 'GEN', 0.50, 1000.00, NULL, NULL, NULL, NULL, NULL, 300.00, 1300.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 15:36:20', 'represent', 'represent', '2026-05-15 15:45:08');
INSERT INTO `tbl_cargo_info_all` (`id`, `uuid`, `freight_id`, `freight_detail_id`, `report_id`, `cal_flag`, `cal_time`, `freight_type`, `prefix`, `cargo_no`, `awb_no`, `awb_carrier`, `international`, `type`, `source_type`, `bill_status`, `check_status`, `ticket_id`, `open_date`, `airline_org_code`, `cargo_dep`, `cargo_dest`, `cargo_type`, `agent_code`, `agent_name`, `flight_no`, `carrier`, `airline_icao`, `airline_icao1`, `flight_date`, `dep`, `dep_name`, `dest`, `dest_name`, `dest1`, `arr`, `flight_nature`, `flight_no2`, `airline_icao2`, `flight_date2`, `carrier2`, `dep2`, `dest2`, `flight_no3`, `airline_icao3`, `carrier3`, `flight_date3`, `dep3`, `dest3`, `rate_class`, `rate_name`, `rate_type`, `currency`, `goods_name`, `goods_type`, `goods_code`, `pc`, `weight`, `charge_weight`, `volume`, `spcode`, `rate`, `flight_fee`, `fuel_fee`, `awc`, `dvc`, `sfc`, `tax`, `other_fee`, `total_amount`, `cal_flight_fee`, `cal_fuel_fee`, `cal_awc`, `cal_dvc`, `cal_sfc`, `cal_msc`, `cal_tax`, `cal_cca_fee`, `cal_other_fee`, `cal_total_other_fee`, `cal_total_amount`, `remark`, `create_time`, `create_by`, `update_by`, `update_time`) VALUES ('2055190527187742721', '9501a24ef52a57913a581c85a490863b', 'aff47c12979dcea16761ecdfd03baf0b', 'e9d486eef3464872ba34b1edebb460f4', 'dc25c2fffa1065523e450adcd52b0537', 1, NULL, 0, '197', '00013016', '197-00013016', NULL, NULL, NULL, NULL, 1, 1, NULL, '2026-05-14', NULL, NULL, NULL, NULL, 'IT', 'iTran', 'TC5402', 'TC', NULL, NULL, '2026-05-14', 'DAR', NULL, 'CAN', NULL, NULL, NULL, 'DAR-CAN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TZS', '1', NULL, 'A', 1, 2999.00, 2999.00, 1.00, 'GEN', 0.50, 1499.50, NULL, NULL, NULL, NULL, NULL, 300.00, 1799.50, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 15:36:20', 'represent', 'represent', '2026-05-15 15:45:08');
INSERT INTO `tbl_cargo_info_all` (`id`, `uuid`, `freight_id`, `freight_detail_id`, `report_id`, `cal_flag`, `cal_time`, `freight_type`, `prefix`, `cargo_no`, `awb_no`, `awb_carrier`, `international`, `type`, `source_type`, `bill_status`, `check_status`, `ticket_id`, `open_date`, `airline_org_code`, `cargo_dep`, `cargo_dest`, `cargo_type`, `agent_code`, `agent_name`, `flight_no`, `carrier`, `airline_icao`, `airline_icao1`, `flight_date`, `dep`, `dep_name`, `dest`, `dest_name`, `dest1`, `arr`, `flight_nature`, `flight_no2`, `airline_icao2`, `flight_date2`, `carrier2`, `dep2`, `dest2`, `flight_no3`, `airline_icao3`, `carrier3`, `flight_date3`, `dep3`, `dest3`, `rate_class`, `rate_name`, `rate_type`, `currency`, `goods_name`, `goods_type`, `goods_code`, `pc`, `weight`, `charge_weight`, `volume`, `spcode`, `rate`, `flight_fee`, `fuel_fee`, `awc`, `dvc`, `sfc`, `tax`, `other_fee`, `total_amount`, `cal_flight_fee`, `cal_fuel_fee`, `cal_awc`, `cal_dvc`, `cal_sfc`, `cal_msc`, `cal_tax`, `cal_cca_fee`, `cal_other_fee`, `cal_total_other_fee`, `cal_total_amount`, `remark`, `create_time`, `create_by`, `update_by`, `update_time`) VALUES ('2057766661637140481', '7c282c10dc7ba06711b2712bbd0d5a89', 'ecd80eaf73ae4cd3efbe1803a360d0b0', '3bec243460b344ec99acc24e59945a35', '77a54b777b694938fc3de07a0fa525a2', 1, NULL, 0, '197', '00013160', '197-00013160', NULL, NULL, NULL, NULL, 1, 1, NULL, '2026-05-15', NULL, NULL, NULL, NULL, 'IT', 'iTran', 'TC0511', 'TC', NULL, NULL, '2026-05-15', 'DAR', NULL, 'CAN', NULL, NULL, NULL, 'DAR-CAN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TZS', '1', NULL, 'A', 5, 5000.00, 5000.00, 10.00, 'GEN', 9.00, 45000.00, NULL, NULL, NULL, NULL, NULL, 300.00, 45300.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22 18:12:58', 'admin', 'admin', '2026-05-22 18:13:43');
INSERT INTO `tbl_cargo_info_all` (`id`, `uuid`, `freight_id`, `freight_detail_id`, `report_id`, `cal_flag`, `cal_time`, `freight_type`, `prefix`, `cargo_no`, `awb_no`, `awb_carrier`, `international`, `type`, `source_type`, `bill_status`, `check_status`, `ticket_id`, `open_date`, `airline_org_code`, `cargo_dep`, `cargo_dest`, `cargo_type`, `agent_code`, `agent_name`, `flight_no`, `carrier`, `airline_icao`, `airline_icao1`, `flight_date`, `dep`, `dep_name`, `dest`, `dest_name`, `dest1`, `arr`, `flight_nature`, `flight_no2`, `airline_icao2`, `flight_date2`, `carrier2`, `dep2`, `dest2`, `flight_no3`, `airline_icao3`, `carrier3`, `flight_date3`, `dep3`, `dest3`, `rate_class`, `rate_name`, `rate_type`, `currency`, `goods_name`, `goods_type`, `goods_code`, `pc`, `weight`, `charge_weight`, `volume`, `spcode`, `rate`, `flight_fee`, `fuel_fee`, `awc`, `dvc`, `sfc`, `tax`, `other_fee`, `total_amount`, `cal_flight_fee`, `cal_fuel_fee`, `cal_awc`, `cal_dvc`, `cal_sfc`, `cal_msc`, `cal_tax`, `cal_cca_fee`, `cal_other_fee`, `cal_total_other_fee`, `cal_total_amount`, `remark`, `create_time`, `create_by`, `update_by`, `update_time`) VALUES ('2057766661641334786', '80f23dd5444139bd7a1b41c16a6ebce9', 'e6413dec3cbff136d9d9120bd64a5c73', '14fcddc246f747298d4add12003bc5b3', '77a54b777b694938fc3de07a0fa525a2', 1, NULL, 0, '197', '21222213', '197-21222213', NULL, NULL, NULL, NULL, 1, 1, NULL, '2026-05-22', NULL, NULL, NULL, NULL, 'IT', 'iTran', 'TC0518', 'TC', NULL, NULL, '2026-05-20', 'DAR', NULL, 'CAN', NULL, NULL, NULL, 'DAR-CAN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TZS', 'GOODS', NULL, 'A', 11, 1000.00, 1833.33, 11.00, 'GEN', -0.20, 1.00, NULL, NULL, NULL, NULL, NULL, 300.00, 301.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22 18:12:58', 'admin', 'admin', '2026-05-22 18:13:43');
INSERT INTO `tbl_cargo_info_all` (`id`, `uuid`, `freight_id`, `freight_detail_id`, `report_id`, `cal_flag`, `cal_time`, `freight_type`, `prefix`, `cargo_no`, `awb_no`, `awb_carrier`, `international`, `type`, `source_type`, `bill_status`, `check_status`, `ticket_id`, `open_date`, `airline_org_code`, `cargo_dep`, `cargo_dest`, `cargo_type`, `agent_code`, `agent_name`, `flight_no`, `carrier`, `airline_icao`, `airline_icao1`, `flight_date`, `dep`, `dep_name`, `dest`, `dest_name`, `dest1`, `arr`, `flight_nature`, `flight_no2`, `airline_icao2`, `flight_date2`, `carrier2`, `dep2`, `dest2`, `flight_no3`, `airline_icao3`, `carrier3`, `flight_date3`, `dep3`, `dest3`, `rate_class`, `rate_name`, `rate_type`, `currency`, `goods_name`, `goods_type`, `goods_code`, `pc`, `weight`, `charge_weight`, `volume`, `spcode`, `rate`, `flight_fee`, `fuel_fee`, `awc`, `dvc`, `sfc`, `tax`, `other_fee`, `total_amount`, `cal_flight_fee`, `cal_fuel_fee`, `cal_awc`, `cal_dvc`, `cal_sfc`, `cal_msc`, `cal_tax`, `cal_cca_fee`, `cal_other_fee`, `cal_total_other_fee`, `cal_total_amount`, `remark`, `create_time`, `create_by`, `update_by`, `update_time`) VALUES ('2057767348609609729', '9a8de5bb00a4d9d691aaacc41ba20334', 'cbd2a0af564f6b5d7f2abd1eadad4965', '517693aa12a917aab435fd1340123feb', NULL, 1, NULL, 4, '197', '00013075', '197-00013075', NULL, NULL, NULL, NULL, 1, NULL, NULL, '2026-05-12', NULL, NULL, NULL, NULL, 'IT', 'iTran', 'TC5402', 'TC', NULL, NULL, '2026-05-12', 'DAR', NULL, 'CAN', NULL, NULL, NULL, 'DAR-CAN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TZS', 'TEST', NULL, 'A', 5, 5000.00, 5000.00, 10.00, 'ICE', 0.00, 0.00, NULL, NULL, NULL, NULL, NULL, NULL, 0.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22 18:15:42', 'admin', NULL, NULL);
INSERT INTO `tbl_cargo_info_all` (`id`, `uuid`, `freight_id`, `freight_detail_id`, `report_id`, `cal_flag`, `cal_time`, `freight_type`, `prefix`, `cargo_no`, `awb_no`, `awb_carrier`, `international`, `type`, `source_type`, `bill_status`, `check_status`, `ticket_id`, `open_date`, `airline_org_code`, `cargo_dep`, `cargo_dest`, `cargo_type`, `agent_code`, `agent_name`, `flight_no`, `carrier`, `airline_icao`, `airline_icao1`, `flight_date`, `dep`, `dep_name`, `dest`, `dest_name`, `dest1`, `arr`, `flight_nature`, `flight_no2`, `airline_icao2`, `flight_date2`, `carrier2`, `dep2`, `dest2`, `flight_no3`, `airline_icao3`, `carrier3`, `flight_date3`, `dep3`, `dest3`, `rate_class`, `rate_name`, `rate_type`, `currency`, `goods_name`, `goods_type`, `goods_code`, `pc`, `weight`, `charge_weight`, `volume`, `spcode`, `rate`, `flight_fee`, `fuel_fee`, `awc`, `dvc`, `sfc`, `tax`, `other_fee`, `total_amount`, `cal_flight_fee`, `cal_fuel_fee`, `cal_awc`, `cal_dvc`, `cal_sfc`, `cal_msc`, `cal_tax`, `cal_cca_fee`, `cal_other_fee`, `cal_total_other_fee`, `cal_total_amount`, `remark`, `create_time`, `create_by`, `update_by`, `update_time`) VALUES ('2057767348622192642', '2e20d2e055fb1615978dcfba0450daef', 'cbd2a0af564f6b5d7f2abd1eadad4965', '517693aa12a917aab435fd1340123feb', NULL, 1, NULL, 4, '197', '00013204', '197-00013204', NULL, NULL, NULL, NULL, 1, NULL, NULL, '2026-05-12', NULL, NULL, NULL, NULL, 'IT', 'iTran', 'TC5402', 'TC', NULL, NULL, '2026-05-14', 'DAR', NULL, 'CAN', NULL, NULL, NULL, 'DAR-CAN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TZS', '一票一议测试', NULL, 'A', 11, 1111.00, 1833.33, 11.00, 'GEN', 0.00, 0.00, NULL, NULL, NULL, NULL, NULL, NULL, 0.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22 18:15:42', 'admin', NULL, NULL);
INSERT INTO `tbl_cargo_info_all` (`id`, `uuid`, `freight_id`, `freight_detail_id`, `report_id`, `cal_flag`, `cal_time`, `freight_type`, `prefix`, `cargo_no`, `awb_no`, `awb_carrier`, `international`, `type`, `source_type`, `bill_status`, `check_status`, `ticket_id`, `open_date`, `airline_org_code`, `cargo_dep`, `cargo_dest`, `cargo_type`, `agent_code`, `agent_name`, `flight_no`, `carrier`, `airline_icao`, `airline_icao1`, `flight_date`, `dep`, `dep_name`, `dest`, `dest_name`, `dest1`, `arr`, `flight_nature`, `flight_no2`, `airline_icao2`, `flight_date2`, `carrier2`, `dep2`, `dest2`, `flight_no3`, `airline_icao3`, `carrier3`, `flight_date3`, `dep3`, `dest3`, `rate_class`, `rate_name`, `rate_type`, `currency`, `goods_name`, `goods_type`, `goods_code`, `pc`, `weight`, `charge_weight`, `volume`, `spcode`, `rate`, `flight_fee`, `fuel_fee`, `awc`, `dvc`, `sfc`, `tax`, `other_fee`, `total_amount`, `cal_flight_fee`, `cal_fuel_fee`, `cal_awc`, `cal_dvc`, `cal_sfc`, `cal_msc`, `cal_tax`, `cal_cca_fee`, `cal_other_fee`, `cal_total_other_fee`, `cal_total_amount`, `remark`, `create_time`, `create_by`, `update_by`, `update_time`) VALUES ('2057767348622192643', 'a3895600376e33b34c9f184161606242', 'cbd2a0af564f6b5d7f2abd1eadad4965', '517693aa12a917aab435fd1340123feb', NULL, 1, NULL, 4, '197', '00013145', '197-00013145', NULL, NULL, NULL, NULL, 1, NULL, NULL, '2026-05-15', NULL, NULL, NULL, NULL, 'IT', 'iTran', 'TC5402', 'TC', NULL, NULL, '2026-05-15', 'DAR', NULL, 'CAN', NULL, NULL, NULL, 'DAR-CAN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TZS', 'TEST', NULL, 'A', 5, 5000.00, 5000.00, 1.00, 'GEN', 0.00, 0.00, NULL, NULL, NULL, NULL, NULL, NULL, 0.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-22 18:15:42', 'admin', NULL, NULL);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
